# Generated by Django 4.2.4 on 2023-08-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='breed',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='favorites',
            field=models.BooleanField(default=False),
        ),
    ]
